### ISSUE TITLE
Evaluation performance

### ISSUE THREAD

**Issue by XuexiongLuoMQ** [benedekrozemberczki/GraphWaveMachine#6]
Hello, thank you for contributing GraphWave code. I run this code and notice that this is only the process of learning the node representations, and does not evaluate performance. However, I try to do this task following the previous work, and I do not achieve. Thus, I hope that you can do this task about this code. If you can, I will thank you very much.

**Comment by JellySUX** [comment]
By performance do you mean the accuracy of the embeddings, or the computational performance? 

The embedding accuracy is discussed in the following papers:
- In the original paper they do performance evaluation - https://arxiv.org/pdf/1710.10321.pdf
- In this paper the performance of other network embedding algorithms is discussed and evaluated - https://arxiv.org/pdf/1911.11726.pdf

Hope this helps

**Comment by XuexiongLuoMQ** [comment]
Thank you for your answer.
But my issue is that I want to explore the node classification performance of the graphwave model on other datasets. And your code only get node embedding representations, I try to do node classification task based your code. But I do not success. So I hope that to make the open source code more usable, you can add the node classification task for graphwave model.

**Comment by JellySUX** [comment]
From the investigations into the use of graphwave that I conducted during my final year of university I found that semi-supervised (such as label spreading) and unsupervised (clustering) ML was not a good use of graphwave due to fairly poor accuracy in a real-world dataset. The dataset used was approximately 270 nodes from the enron dataset labelled with the individual's job title, with the aim of predicting job-title from the graph structure. The job titles were "Employee", "Manager", and "President, Director, or CEO (PDCEO)".

![Unsupervised learning performance](https://user-images.githubusercontent.com/15263318/88379674-4a655000-cd9b-11ea-9ab7-f71c1f81cc92.png)

![Label spreading performance](https://user-images.githubusercontent.com/15263318/88379787-6c5ed280-cd9b-11ea-9018-6c9fc1020f85.png)


Supervised learning approaches, such as using XGBoost, were fairly effective in comparison but still did not yield 'good' overall accuracy, however this is not necessarily the fault of the approach, but potentially the relatively small and potentially noisy dataset used. This approach also requires a large amount of labelled data, which would not be a good use case for graphwave in the first place as graphwave is designed for unsupervised role detection. Perhaps another algorithm would be more suitable in this case, as it would be able to take advantage of known labels to extract behaviour 'fingerprints' that would more strongly correlate with each class.

![Supervised learning performance](https://user-images.githubusercontent.com/15263318/88379621-34f02600-cd9b-11ea-9d59-18b89e908904.png)

In the dataset I used, the best approach I found was simply using K-NN, where K could be as low as a single other node and would still provide relatively good accuracy.

![Single Nearest Neighbour performance](https://user-images.githubusercontent.com/15263318/88380072-c495d480-cd9b-11ea-94de-b96b258122e2.png)

Additionally the idea of an ordered set of likely classes (which could be evaluated similarly to a search engine's ranking system) using K-NN was initially investigated, but needed more testing than I had time for.

Hope this helps, and I have also created a distributed graphwave implementation to help speed up the learning times as this implementation, whilst very good, does not take advantage of the embarrassingly parallel nature of most of the graphwave algorithm.

**Comment by XuexiongLuoMQ** [comment]
Thank you very much.  I learned a lot from your answer analysis. I want to do node classification task on Cora dataset by using your code. But my code allways dose not run in the part of node classification code. So I'd like to ask for your help. I hope that you can give the code of node classification based on your graphwave model. Thank you much.

**Comment by JellySUX** [comment]
This is taking bits from what i used, however is not entirely the same. But it should give you an idea of how I approached it.
```python3
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from pprint import pprint
from sklearn.metrics import classification_report

gw_res = pd.read_csv("gwres.csv") # output from graphwave algorithm
roles = pd.read_csv("roles.csv") # order matches gwres order.

df_all = gw_res
df_all['role'] = roles


pca = PCA(n_components=0.99) # keep 99% of variance 
emb = pca.fit_transform(StandardScaler().fit_transform(gw_res))

clf = SVC()
le = LabelEncoder()

X = gw_res
y = le.fit_transform(df_all['role'])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

clf.fit(X_train, y_train)
preds = clf.predict(X_test)
pprint(confusion_matrix(y_test, preds))
print(classification_report(y_test, preds))
```

**Comment by XuexiongLuoMQ** [comment]
Hello, I am sorry to reply your message now. I read your answer above, but I do not get this result. This is my real problem according the learned node embedding from your code. I think that you see this figure, and you can know my problem. Thus, I hope that you can know how to solve this problem. Due to the learned node embedding from your code, I would like to evaluate the learned node embedding through the node classification.
![](https://img-blog.csdnimg.cn/20200820170132262.PNG?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L2x1b3h1ZXhpb25n,size_16,color_FFFFFF,t_70)
###    Run Error: TypeError: Singleton array array(<_io.TextIOWrapper name='../output/wiki_embedding.txt' mode='r' encoding='cp936'>, dtype=object) cannot be considered a valid collection.

**Comment by benedekrozemberczki** [comment]
The link is dead.

**Comment by JellySUX** [comment]
EDIT:
what does your node_classification_F1 function expect? Currently you are passing it a python file object, rather than a Numpy Array or a Pandas Dataframe which may be what the function expects

**Comment by XuexiongLuoMQ** [comment]
Here, this function code:

read_label()

    `def read_label(inputFileName):
        f = open(inputFileName, 'r')
        lines = f.readlines()
        f.close()
        N = len(lines)
        y = np.zeros(N, dtype=int)
        for line in lines:
            l = line.strip('\n\r').split(' ')
            y[int(l[0])] = int(l[1])
        return y`

node_classification_F1()

    `def node_classification_F1(Embeddings, y):
        macro_f1_avg = 0
        micro_f1_avg = 0
        for i in range(10):
           rnd = np.random.randint(2018)
           macro_f1, micro_f1 = multiclass_node_classification_eval(Embeddings, y, 0.7, rnd)
           macro_f1_avg += macro_f1
           micro_f1_avg += micro_f1
        macro_f1_avg /= 10
        micro_f1_avg /= 10
        print('Macro_f1 average value: ' + str(macro_f1_avg))
        print('Micro_f1 average value: ' + str(micro_f1_avg))`

multiclass_node_classification_eval()

    `def multiclass_node_classification_eval(X, y, ratio=0.2, rnd=2018):
       warnings.filterwarnings('ignore')
      X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=ratio, random_state=rnd)
      clf = LinearSVC()
      clf.fit(X_train, y_train)
      y_pred = clf.predict(X_test)
      macro_f1 = f1_score(y_test, y_pred, average='macro')
      micro_f1 = f1_score(y_test, y_pred, average='micro')
      return macro_f1, micro_f1`

I hope that you can solve this problem. Thank you very much.

**Comment by JellySUX** [comment]
try changing `embeddings = open(fn,'r')`
to
`embeddings = pandas.read_csv(fn)`

**Comment by XuexiongLuoMQ** [comment]
Thank you very much. According your advice, I get the result, Thank you again.
